version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: lti-postgres
    environment:
      POSTGRES_DB: lti_ats
      POSTGRES_USER: lti_user
      POSTGRES_PASSWORD: lti_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lti_user -d lti_ats"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: ./packages/backend
      dockerfile: Dockerfile
    container_name: lti-backend
    environment:
      DATABASE_URL: postgresql://lti_user:lti_password@postgres:5432/lti_ats
      PORT: 3001
      NODE_ENV: development
    ports:
      - "3001:3001"
    depends_on:
      postgres:
        condition: service_healthy
    volumes:
      - ./packages/backend:/app
      - /app/node_modules
    command: npm run dev

  frontend:
    build:
      context: ./packages/frontend
      dockerfile: Dockerfile
    container_name: lti-frontend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./packages/frontend:/app
      - /app/node_modules
    command: npm start

volumes:
  postgres_data: 